/* Registering the engine with the machine it is installed on.
 *
 * Deliberately not reproduced. The original writes an eci.ini file next to
 * itself saying where it is, what version it is, and which voices and
 * phonemes it offers, so that something else can read it later. All four
 * of these are reached only from reg(), an entry point an installer calls
 * once; nothing in a speaking engine calls it, nothing reads back what it
 * writes, and the settings the engine actually runs on are the built-in
 * ones in eci_ini_enus.c rather than anything in that file.
 *
 * The rules name all four in their table of primitives, so the table needs
 * an address for each. These are those addresses and nothing more. A port
 * whose targets include a games console and a music player has nowhere to
 * write such a file and no installer to write it.
 *
 * They answer the way the original answers on a machine where it has not
 * been told an install directory, which is every machine that has not run
 * its installer: refused. The fourth is nought because the original's own
 * is an empty function that answers nought.
 */

#include "evv_arena.h"
#include <stdint.h>
#include "delta.h"

/* What the original answers when it cannot write the file. */
#define REFUSED (-1)

int32_t registerLanguage(delta_state *d, ...)
{
    (void)d;
    return REFUSED;
}

int32_t registerPhoneme(delta_state *d, ...)
{
    (void)d;
    return REFUSED;
}

int32_t registerVoice(delta_state *d, ...)
{
    (void)d;
    return REFUSED;
}

int32_t registerSAPIVoice(delta_state *d, ...)
{
    (void)d;
    return 0;
}

/* Generated by tools/evv-wrapgen.py. Do not edit.
 *
 * One wrapper for each primitive the interpreter calls through call_entry,
 * turning the slot values it hands over back into the pointers the primitive
 * declares. Only a relative arena needs them: with an absolute one a slot
 * value IS the address and EVV_AT is the identity.
 */

int32_t evvw_registerLanguage(int32_t a0, int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24)
{
    return (int32_t)registerLanguage(EVV_AT(delta_state *, a0), a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24);
}

int32_t evvw_registerPhoneme(int32_t a0, int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24)
{
    return (int32_t)registerPhoneme(EVV_AT(delta_state *, a0), a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24);
}

int32_t evvw_registerSAPIVoice(int32_t a0, int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24)
{
    return (int32_t)registerSAPIVoice(EVV_AT(delta_state *, a0), a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24);
}

int32_t evvw_registerVoice(int32_t a0, int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21, int32_t a22, int32_t a23, int32_t a24)
{
    return (int32_t)registerVoice(EVV_AT(delta_state *, a0), a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24);
}
